[bar]
scale = 0.75
background-opacity = 0

[[bar.layout]]
monitor = "*"
show = true
left = ["hyprland-workspaces"]
center = ["clock"]
right = [
    "bluetooth",
    "network",
    "microphone",
    "volume",
    "cpu",
    "ram",
    "battery",
    "keyboard-input",
    "power",
]

[styling]
scale = 1.0

[modules.hyprland-workspaces]
workspace-padding = 1.0

[modules.keyboard-input]
icon-show = false

[modules.power]
border-show = true
icon-bg-color = "green"
left-click = "wleave -b 1"
