$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

# exec-once = $terminal
# exec-once = nm-applet &
# exec-once = waybar & hyprpaper & firefox

exec-once = waybar
exec-once = swww-daemon --format xrgb
exec-once = swww img ~/.config/hypr/wallpaper/Space-Nebula.png --transition-type grow --transition-duration 1.5 --transition-fps 60
