$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun

exec-once = waybar
exec-once = swaync
exec-once = swww-daemon --format xrgb
exec-once = swww img ~/.config/hypr/wallpaper/Space-Nebula.png --transition-type grow --transition-duration 1.5 --transition-fps 60
